## Day - 8 \\ 21-04-2023

In [2]:
import numpy as np

In [52]:
a = np.array([8,6,5,])

In [139]:
k = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [140]:
m = np.array([[[4,41],[8,81],[7,71]],
              [[3,31],[1,11],[5,51]],
              [[6,61],[9,91],[13,131]]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [141]:
m.shape

(3, 3, 2)

In [142]:
k[1,0:3:1]

array([9, 3, 5])

In [143]:
k[1,:]

array([9, 3, 5])

In [144]:
k[0:4:1,2]

array([ 4,  5, 17,  8])

In [145]:
k[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [146]:
k[:,2:3]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [147]:
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [148]:
m[1:,1:,0:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [149]:
m[1:,0:1,:]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [150]:
k+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [151]:
k.dtype

dtype('int32')

In [152]:
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [153]:
k[0,:] = [23,34,45]
k

array([[23, 34, 45],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [154]:
k[:,0] = [1,2,3,4]
k

array([[ 1, 34, 45],
       [ 2,  3,  5],
       [ 3, 15, 17],
       [ 4, 31,  8]])

In [155]:
k[:,1:2]=[[5],[6],[7],[8]]
k

array([[ 1,  5, 45],
       [ 2,  6,  5],
       [ 3,  7, 17],
       [ 4,  8,  8]])

In [156]:
np.append(k,[[99,88,77]],axis = 0)

array([[ 1,  5, 45],
       [ 2,  6,  5],
       [ 3,  7, 17],
       [ 4,  8,  8],
       [99, 88, 77]])

In [157]:
np.append(k,[[44],[33],[22],[11]],axis = 1)

array([[ 1,  5, 45, 44],
       [ 2,  6,  5, 33],
       [ 3,  7, 17, 22],
       [ 4,  8,  8, 11]])

In [158]:
np.delete(k,1,1)

array([[ 1, 45],
       [ 2,  5],
       [ 3, 17],
       [ 4,  8]])

In [159]:
k

array([[ 1,  5, 45],
       [ 2,  6,  5],
       [ 3,  7, 17],
       [ 4,  8,  8]])

In [160]:
k.reshape(3,4)

array([[ 1,  5, 45,  2],
       [ 6,  5,  3,  7],
       [17,  4,  8,  8]])

In [161]:
k.dtype

dtype('int32')

In [165]:
a1 = np.array([3.5,6.8,9])
a1.dtype

dtype('float64')

In [166]:
a1.astype('uint16')

array([3, 6, 9], dtype=uint16)

In [167]:
a1.dtype

dtype('float64')

# Nutshell :-
## # Creating Array -
- np.array()
- np.ones()
- np.zeros()
- np.random.randint()
- np.arange()
- np.linespace()

## Day - 9 \\ 24-04-2023

In [4]:
np.ones((2,3),)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(0,10,10,dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [23]:
np.random.randint(1,40,[2,4])

array([[24,  5, 27,  1],
       [32, 26, 16, 14]])

In [24]:
np.random.randint(1,40,10)

array([39, 25,  5,  5, 28, 32, 27,  5, 39,  3])

In [27]:
np.random.randint(1,1000,[3,2,4])

array([[[975,  21, 831, 805],
        [681, 738, 106, 915]],

       [[692, 266, 753, 531],
        [521, 881, 133, 540]],

       [[436, 594, 889, 141],
        [527, 815, 670, 609]]])

In [34]:
np.random.seed(100)
np.random.randint(1,1000,[4,3])

array([[521, 793, 836],
       [872, 856,  80],
       [945, 907, 351],
       [949, 867,  54]])

In [40]:
np.random.rand(3,4)

array([[0.59884338, 0.60380454, 0.10514769, 0.38194344],
       [0.03647606, 0.89041156, 0.98092086, 0.05994199],
       [0.89054594, 0.5769015 , 0.74247969, 0.63018394]])

In [55]:
np.loadtxt(r'C:\Users\Kumud Jain\OneDrive\Desktop\Upflairs\Stuff\some.txt',dtype=str)

array(['DAR', 'KE', 'AAGE', 'JEET', 'HAI'], dtype='<U4')

In [57]:
np.loadtxt(r'C:\Users\Kumud Jain\OneDrive\Desktop\Upflairs\Stuff\more.txt')

array([[1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.]])

In [58]:
p = np.random.rand(3,4)

In [61]:
np.savetxt('new.txt',p,delimiter='==')