## Day - 7 \\ 11-04-2023

# Working with Python Modules

In [4]:
# To install via terminal if package/module not found
# !python -m pip install numpy
# !pip install numpy

In [30]:
import numpy as np

import my_file
my_file.abc()

In [14]:
import new_pack
import new_pack.new1
new_pack.new1.xyz()

xyz


In [15]:
import keyword

In [19]:
keyword.iskeyword('if')

True

In [20]:
import keyword as kw

In [21]:
kw.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [26]:
from keyword import kwlist, iskeyword
kwlist , iskeyword('if')

(['False',
  'None',
  'True',
  '__peg_parser__',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield'],
 True)

In [34]:
a = np.array([])
a

array([], dtype=float64)

In [35]:
b = np.array([3,4,5,6,7,8,9])
b

array([3, 4, 5, 6, 7, 8, 9])

In [38]:
len(a),len(b)

(0, 7)

In [40]:
b.dtype

dtype('int32')

In [41]:
b.shape

(7,)

In [42]:
b.size

7

In [43]:
b.ndim

1

In [44]:
type(a)

numpy.ndarray

In [45]:
type(b)

numpy.ndarray

In [70]:
c = np.array([[34,56,1],[67,90,2],[78,54,3]])
c

array([[34, 56,  1],
       [67, 90,  2],
       [78, 54,  3]])

In [61]:
c.ndim

2

In [67]:
c.shape

(3, 3)

In [73]:
f = np.array([[[34,4],[56,5],[1,7]],[[67,8],[90,32],[2,45]],[[78,56],[54,89],[3,89]],[[34,7],[56,23],[67,9]]])
f

array([[[34,  4],
        [56,  5],
        [ 1,  7]],

       [[67,  8],
        [90, 32],
        [ 2, 45]],

       [[78, 56],
        [54, 89],
        [ 3, 89]],

       [[34,  7],
        [56, 23],
        [67,  9]]])

In [74]:
f.shape

(4, 3, 2)

In [75]:
f.ndim

3

In [78]:
c.sum(axis=1)

array([ 91, 159, 135])

In [79]:
c.mean(axis=1)

array([30.33333333, 53.        , 45.        ])

In [80]:
c

array([[34, 56,  1],
       [67, 90,  2],
       [78, 54,  3]])

In [82]:
c[0][1] # 56

56

In [84]:
c[0:2,-1]

array([1, 2])

In [85]:
c[0:2,-1:]

array([[1],
       [2]])